export const bookGenres: string[] = [
  "Mystery",
  "Thriller",
  "Science Fiction",
  "Fantasy",
  "Romance",
  "Horror",
  "Historical Fiction",
  "Dystopian",
  "Adventure",
  "Non-fiction",
  "Crime",
  "Biography",
  "Humor",
  "Poetry",
  "Graphic Novel",
];
